# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lollypop Lawns
email: lollypoplawns@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lollypop Lawns is a lady-owned lawn care serving Allandale, Brentwood, and Crestview neighborhoods in Austin, Texas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
